Нужно больше функций
htmlacademy-javascript/1668659-kekstagram-23 pull request #2
Opened 2021-05-31 14:58 UTC by kartsivadze-l

2021-05-31 16:44 UTC, ademaro commented on js/main.js
> + */
Отлично! Только jsDoc прям перед самой функцией давай писать, прям вплотную

2021-05-31 16:45 UTC, ademaro commented on js/main.js
> +  if (stringLength <= maxLength) {
можем просто `return (stringLength <= maxLength)`

2021-05-31 16:47 UTC, ademaro commented on js/main.js
> +let result;
зачем нам лишний result вне функции? Давай уберём внутрь или сразу делай return, тогда и эта переменная не понадобится)

2021-05-31 16:47 UTC, ademaro requested changes
Давай подправим немного, что бы совсем чистый код был. А так — всё круто, молодец!

2021-05-31 16:58 UTC, kartsivadze-l commented on js/main.js
> +  if (stringLength <= maxLength) {
я правильно понимаю, что если я напишу return (stringLength <= maxLength) вместо всех условий, то, если длина строки <= макс длине, функция вернет true, а в противном случае – false?

2021-06-01 21:40 UTC, ademaro commented on js/main.js
> +  if (min < max) {
на будущее вариант:
```js
if (min < max) {
  [min, max] = [max, min];
}
```
Смогли бы сократить сильно код))

2021-06-01 21:40 UTC, ademaro approved these changes
Отлично, летим дальше, ПР закрываю!

2021-06-01 21:40 UTC, merged